FIXED: Does not handle "animatedfriction" section in PHY file.
If the animatedfriction section exists, then the editparams section is skipped.
This can cause this error message to appear when recompiling:
ERROR: Rotation constraint on bone "ValveBiped.Bip01_Pelvis" which has no parent!!!